### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by manishtomar**
This builds image with pgformatter in it. The tool can then be run as `cat file.sql | docker run --rm -a stdin -a stdout -i darold/pgformatter -`. This is assuming you've image uploaded at `darold/pgformatter`

### CODE REVIEW

**Comment by darold** [comment]
Hi Manish,

Can you explain me the interest of running pgFormatter through a container? I can understand for the CGI mode (apache install, etc) but to execute a single Perl script that do not have any dependency I can't find any reason to not install pgFormatter and use a container each time.

Regards,

**Comment by manishtomar** [comment]
@darold I looked at installation instructions and was not comfortable running `sudo make install`. To quickly start using it I created a container and have been using it. Honestly, I've never used perl and didn't realize that this script does not have dependencies.

**Comment by darold** [comment]
Like most of Perl projects you are not forced to use sudo to install it in the Perl site directory. You can install it in any directory created by the current user or in /tmp if you want. For example:
```
$ mkdir /tmp/perl
$ perl Makefile.PL DESTDIR=/tmp/perl
[...]
Installing /tmp/perl/usr/local/man/man1/pgcluu.1
Installing /tmp/perl/usr/local/bin/pgcluu_collectd
Installing /tmp/perl/usr/local/bin/pgcluu
Appending installation info to /tmp/perl/usr/local/lib/x86_64-linux-gnu/perl/5.26.1/perllocal.pod
```
then add `/tmp/perl/usr/local/bin/` to you path or call the pgCluu scripts with absolute path.

**Comment by manishtomar** [comment]
@darold Great. It would really help to have above instructions added in README. In any case, I leave the state of this PR up to you. Please feel free to close it.

**Comment by nyurik** [comment]
@darold hi, thanks for the great project. If possible, could you reconsider creating a dockerfile and making docker hub automatically build it for you? It would simplify many CI usecases.  If i want to use your tool to format my code, or to use it as part of the CI to validate that the submission is confirming to the linting rules, I can just run a single docker command (from a makefile) without 1) making sure i have perl installed, 2) downloading your tool and ensuring the latest version.

Docker hub can autobuild it for you with just a few clicks to setup.

Thanks!

**Comment by michael-robbins** [comment]
@darold  I'd really recommend pursuing this again, wrapping the tool up into a docker image means I don't need *any* dependencies (referring to Perl here) on my server apart from docker. A lot of CI tooling out there also supports running docker images at various stages in lieu of having to have all your dependencies installed onto each 'CI runner'.

This would only benefit the users of pgFormatter with no arguably no downsides. As @nyurik mentioned, you can even have Dockerhub auto build it so it's a 'set and forget', you pin the version of Perl you're comfortable with and away you go!

**Comment by darold** [comment]
Yes, will do, the argument is valuable. Just give me few more time to be back to pgFormatter.

**Comment by darold** [comment]
@manishtomar finally your patch have been merged with commit d5ffbbc, thanks a lot for the contribution.

**Pull request closed without merging**
